"use client";
import { useMemo, useState } from "react";
import { postAction, mowJson } from "../lib/api";
import { Icon } from "./Icon";

const stages=["Prepare","Copy / open","Paste","Validate","Review"];
export function ManualBridge(){
  const [state,setState]=useState("PROMPT_READY");
  const [prompt,setPrompt]=useState("Recipe: social_post_create\nObjective: create a useful marketing post\nAudience: SMB employers\nConstraints: no fabricated claims; clear CTA; evidence-aware\nReturn structured JSON.");
  const [result,setResult]=useState("");
  const [parsed,setParsed]=useState<any>(null);
  const [qa,setQa]=useState<any>(null);
  const [copied,setCopied]=useState(false);
  const [error,setError]=useState("");
  const [requestId,setRequestId]=useState("");
  const stageIndex=useMemo(()=>({PROMPT_READY:0,COPIED:1,EXTERNAL_AI_OPEN:1,RESPONSE_EXPECTED:2,RESPONSE_PASTED:2,PARSING:3,PARSED:3,QA_PENDING:3,REVIEW_PENDING:4}[state]??0),[state]);
  async function prepare(){setError("");try{const response=await postAction("/api/manual/prepare",{recipeId:"social_post_create",taskType:"CREATIVE_GENERATION",dataClass:"LOW_SENSITIVITY",prompt});const id=response.requestId||crypto.randomUUID();setRequestId(id);setPrompt(JSON.stringify(response.prompt||prompt,null,2));setState("PROMPT_READY");return id;}catch(e){setError(e instanceof Error?e.message:"Unable to prepare prompt");return "";}}
  async function copy(){try{await navigator.clipboard?.writeText(prompt);setCopied(true);setState("COPIED");}catch{setError("Clipboard access was blocked. Select and copy the prompt manually.");}}
  async function parse(){setError("");if(!result.trim()){setState("RESPONSE_EXPECTED");return;}setState("PARSING");try{const json=JSON.parse(result);setParsed(json);setState("PARSED");}catch{setParsed(null);setError("INVALID_OUTPUT: the pasted response is not valid JSON. Work is preserved; correct the response and try again.");setState("RESPONSE_PASTED");}}
  async function openExternalAi(){const id=requestId||await prepare();if(!id)return;try{await postAction("/api/manual/event",{requestId:id,eventType:"MANUAL_AI_OPENED"});setState("EXTERNAL_AI_OPEN");}catch(e){setError(e instanceof Error?e.message:"Unable to record browser-AI handoff");}}
  async function sendToReview(){if(!parsed){setError("Parse a structured response before sending it to review.");return;}if(!qa){setError("Run deterministic QA before sending to review.");return;}try{await postAction("/api/manual/event",{requestId:requestId||"manual-review",eventType:"MANUAL_AI_REVIEW_PENDING"});setState("REVIEW_PENDING");}catch(e){setError(e instanceof Error?e.message:"Unable to record review handoff");}}
  async function runQa(){if(!parsed){setError("Parse a structured response before running QA.");return;}setState("QA_PENDING");try{const out=await mowJson<any>("/api/ai/qa",{method:"POST",body:JSON.stringify({audience:"SMB employers",objective:"Create a useful marketing post",platform:"Relevant platform",cta:parsed?.CTA||parsed?.cta||"",body:JSON.stringify(parsed),sourceRefs:[],assetRefs:[],approvalRequired:true})});setQa(out);setState("REVIEW_PENDING");}catch(e){setError(e instanceof Error?e.message:"QA failed");}}
  return <div className="page-shell"><section className="page-header page-header-rich"><div><div className="eyebrow">System / Manual AI Bridge</div><div className="title-line"><div className="title-icon"><Icon name="panel" size={20}/></div><div><h1>Manual AI Bridge</h1><p>A deliberate, human-controlled path for browser AI. The Workbench prepares context; you decide what leaves the browser.</p></div></div></div><span className="status-pill status-good">{state}</span></section>
    <section className="card stepper-card"><div className="stepper">{stages.map((s,i)=><div className={`stepper-item ${i<=stageIndex?"active":""}`} key={s}><span>{i+1}</span><strong>{s}</strong>{i<stages.length-1&&<i/>}</div>)}</div></section>
    <div className="manual-layout"><section className="card card-pad"><div className="section-title"><div><div className="surface-kicker">01 · Prepare</div><h2>Prompt package</h2><p>Safe, structured context ready for a deliberate handoff.</p></div><span className="badge">LOW SENSITIVITY</span></div><textarea className="code-editor" value={prompt} onChange={(e:any)=>setPrompt(e.target.value)} /><div className="button-row"><button className="btn" onClick={prepare}><Icon name="refresh" size={14}/> Rebuild package</button><button className="btn accent" onClick={copy}><Icon name="copy" size={14}/>{copied?"Copied":"Copy prompt"}</button><button className="btn" onClick={openExternalAi}><Icon name="external" size={14}/> I opened external AI</button></div></section>
      <section className="card card-pad"><div className="section-title"><div><div className="surface-kicker">02 · Response</div><h2>Paste and validate</h2><p>Nothing becomes final merely because text was pasted.</p></div><span className="badge status-warn">VALIDATION REQUIRED</span></div><textarea className="result-editor" value={result} onChange={(e:any)=>{setResult(e.target.value);setState(e.target.value?"RESPONSE_PASTED":"RESPONSE_EXPECTED")}} placeholder='Paste the JSON response from the browser AI here.'/><div className="button-row"><button className="btn" onClick={parse}><Icon name="play" size={14}/> Parse JSON</button><button className="btn" onClick={runQa}><Icon name="shield" size={14}/> Run deterministic QA</button><button className="btn accent" onClick={sendToReview} disabled={!qa||!parsed}><Icon name="check" size={14}/> Send to review</button></div></section></div>
    {error&&<div className="notice notice-bad"><Icon name="warning" size={14}/><span>{error}</span></div>}
    <section className="card card-pad bridge-evidence"><div className="section-title"><div><div className="surface-kicker">03 · Evidence</div><h2>Validation trail</h2><p>Keep the response, parsed structure and QA outcome visible.</p></div></div><div className="evidence-grid"><div className="evidence-card"><span>Parsed</span><strong>{parsed?"YES":"NOT YET"}</strong><pre>{parsed?JSON.stringify(parsed,null,2):"No parsed object"}</pre></div><div className="evidence-card"><span>Deterministic QA</span><strong>{qa?"RUN":"NOT RUN"}</strong><pre>{qa?JSON.stringify(qa,null,2):"QA not run"}</pre></div><div className="evidence-card"><span>Human decision</span><strong>{state==="REVIEW_PENDING"?"PENDING":"NOT STARTED"}</strong><p>Approval remains a human action; external browsing is never automated silently.</p></div></div></section>
  </div>
}
