import { AiGateway,GeminiAdapter,HuggingFaceAdapter,NoAiProvider,OpenRouterAdapter } from "@mow/ai-gateway";
import { canPublish,canTransitionContent } from "@mow/core";
import { evaluateDeterministically,UnavailableKevEvaluator,HttpKevEvaluator } from "@mow/evaluators";
export interface Env{DB:D1Database;ASSETS:R2Bucket;JOBS:Queue;OPENROUTER_API_KEY?:string;GEMINI_API_KEY?:string;AUTH_SECRET?:string;DEMO_AUTH?:string;HF_SPACE_URL?:string;KEV_ENDPOINT_URL?:string;FRONTEND_ORIGIN?:string;OPENROUTER_READY?:string;GEMINI_READY?:string;HF_READY?:string;OPENROUTER_MODEL_ID?:string;GEMINI_MODEL_ID?:string;}
type RequestContext={workspaceId:string;userId:string;email?:string};
function json(data:unknown,init:ResponseInit={},origin="*"):Response{return new Response(JSON.stringify(data),{...init,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store","access-control-allow-origin":origin,...(init.headers||{})}});}
async function ctxFrom(request:Request,env:Env):Promise<RequestContext>{
  if(env.DEMO_AUTH==="true") return {workspaceId:request.headers.get("x-mow-workspace")||"demo-workspace",userId:request.headers.get("x-mow-user")||"demo-user"};
  const email=request.headers.get("cf-access-authenticated-user-email");
  if(!email) throw Object.assign(new Error("AUTH_REQUIRED"),{status:401});
  const member=await env.DB.prepare("SELECT m.workspace_id AS workspaceId,m.user_id AS userId FROM memberships m JOIN users u ON u.id=m.user_id WHERE lower(u.email)=lower(?1)").bind(email).first<{workspaceId:string;userId:string}>();
  if(!member) throw Object.assign(new Error("WORKSPACE_MEMBERSHIP_REQUIRED"),{status:403});
  return {workspaceId:member.workspaceId,userId:member.userId,email};
}
function str(body:any,k:string,requiredOrAlias:boolean|string=true):string{const alias=typeof requiredOrAlias==="string"?requiredOrAlias:undefined;const required=typeof requiredOrAlias==="boolean"?requiredOrAlias:true;const raw=body?.[k]??(alias?body?.[alias]:undefined);const v=typeof raw==="string"?raw.trim():raw==null?"":String(raw);if(required&&!v)throw Object.assign(new Error(`VALIDATION_${k.toUpperCase()}`),{status:400});return v;}
function arr(body:any,k:string):string[]{return Array.isArray(body?.[k])?body[k].filter((v:any)=>typeof v==="string"):typeof body?.[k]==="string"&&body[k].trim()?[body[k].trim()]:[];}

async function withIdempotency<T>(env:Env,ctx:RequestContext,request:Request,action:string,work:()=>Promise<T>):Promise<T>{
  const key=request.headers.get("idempotency-key"); if(!key)throw Object.assign(new Error("IDEMPOTENCY_KEY_REQUIRED"),{status:400});
  const existing=await env.DB.prepare("SELECT result_json FROM idempotency_records WHERE key=?1 AND workspace_id=?2 AND action=?3").bind(key,ctx.workspaceId,action).first<{result_json:string}>();
  if(existing?.result_json&&existing.result_json!=="__PENDING__")return JSON.parse(existing.result_json) as T;
  try{await env.DB.prepare("INSERT INTO idempotency_records (key,workspace_id,action,result_json,created_at) VALUES (?1,?2,?3,'__PENDING__',?4)").bind(key,ctx.workspaceId,action,new Date().toISOString()).run();}
  catch{const retry=await env.DB.prepare("SELECT result_json FROM idempotency_records WHERE key=?1 AND workspace_id=?2 AND action=?3").bind(key,ctx.workspaceId,action).first<{result_json:string}>();if(retry?.result_json&&retry.result_json!=="__PENDING__")return JSON.parse(retry.result_json) as T;throw Object.assign(new Error("IDEMPOTENCY_IN_PROGRESS"),{status:409});}
  try{const result=await work();await env.DB.prepare("UPDATE idempotency_records SET result_json=?1,resource_id=?2 WHERE key=?3 AND workspace_id=?4 AND action=?5").bind(JSON.stringify(result),(result as any)?.id||null,key,ctx.workspaceId,action).run();return result;}catch(error){await env.DB.prepare("DELETE FROM idempotency_records WHERE key=?1 AND workspace_id=?2 AND action=?3 AND result_json='__PENDING__'").bind(key,ctx.workspaceId,action).run();throw error;}
}

async function audit(env:Env,ctx:RequestContext,eventType:string,resourceType:string,resourceId:string,result:unknown){await env.DB.prepare("INSERT INTO audit_events (id,workspace_id,event_type,actor_id,resource_type,resource_id,result_json,created_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?8)").bind(crypto.randomUUID(),ctx.workspaceId,eventType,ctx.userId,resourceType,resourceId,JSON.stringify(result),new Date().toISOString()).run();}
async function dashboard(env:Env,ctx:RequestContext){const [tasks,content,jobs]=await Promise.all([env.DB.prepare("SELECT COUNT(*) AS c FROM tasks WHERE workspace_id=?1 AND status IN ('TODAY','IN_PROGRESS','REVIEW')").bind(ctx.workspaceId).first<{c:number}>(),env.DB.prepare("SELECT COUNT(*) AS c FROM content_items WHERE workspace_id=?1 AND status IN ('DRAFT','QA')").bind(ctx.workspaceId).first<{c:number}>(),env.DB.prepare("SELECT COUNT(*) AS c FROM jobs WHERE workspace_id=?1 AND status IN ('FAILED','DEAD_LETTER')").bind(ctx.workspaceId).first<{c:number}>()]);return {workspaceId:ctx.workspaceId,tasksToday:tasks?.c??0,contentAttention:content?.c??0,failedJobs:jobs?.c??0};}
async function quotaFor(env:Env,ctx:RequestContext,provider:string):Promise<number|undefined>{if(provider!=="openrouter")return undefined;const day=new Date().toISOString().slice(0,10);const row=await env.DB.prepare("SELECT requests FROM provider_quota_snapshots WHERE workspace_id=?1 AND provider=?2 AND period=?3 ORDER BY created_at DESC LIMIT 1").bind(ctx.workspaceId,provider,day).first<{requests:number}>();return Math.max(0,45-(row?.requests??0));}
async function recordQuota(env:Env,ctx:RequestContext,provider:string,response:{usage?:{inputTokens?:number;outputTokens?:number}}){const day=new Date().toISOString().slice(0,10);const current=await env.DB.prepare("SELECT id,requests,input_tokens,output_tokens FROM provider_quota_snapshots WHERE workspace_id=?1 AND provider=?2 AND period=?3 ORDER BY created_at DESC LIMIT 1").bind(ctx.workspaceId,provider,day).first<{id:string;requests:number;input_tokens:number|null;output_tokens:number|null}>();const now=new Date().toISOString();if(current){const next=current.requests+1;await env.DB.prepare("UPDATE provider_quota_snapshots SET requests=?1,input_tokens=?2,output_tokens=?3,quota_state=?4,created_at=?5 WHERE id=?6").bind(next,(current.input_tokens??0)+(response.usage?.inputTokens??0),(current.output_tokens??0)+(response.usage?.outputTokens??0),next>=45?"LIMITED":next>=38?"NEAR_LIMIT":"AVAILABLE",now,current.id).run();}else{await env.DB.prepare("INSERT INTO provider_quota_snapshots (id,workspace_id,provider,period,requests,input_tokens,output_tokens,estimated_cost,quota_state,created_at) VALUES (?1,?2,?3,?4,1,?5,?6,0,?7,?8)").bind(crypto.randomUUID(),ctx.workspaceId,provider,day,response.usage?.inputTokens??0,response.usage?.outputTokens??0,"AVAILABLE",now).run();}}
async function generate(env:Env,request:Request,ctx:RequestContext){
  const body=await request.json() as any; const requestId=body.requestId||crypto.randomUUID(); const openRemaining=await quotaFor(env,ctx,"openrouter"); const registry=await env.DB.prepare("SELECT provider_id,state FROM ai_providers WHERE workspace_id=?1").bind(ctx.workspaceId).all(); const verified=(id:string)=>registry.results?.some((r:any)=>r.provider_id===id&&r.state==="READY")===true;
  const gateway=new AiGateway([new OpenRouterAdapter(env.OPENROUTER_API_KEY,env.OPENROUTER_MODEL_ID||"openai/gpt-oss-20b:free",env.OPENROUTER_READY==="true"&&verified("openrouter")),new GeminiAdapter(env.GEMINI_API_KEY,env.GEMINI_MODEL_ID||"gemini-2.5-flash-lite",env.GEMINI_READY==="true"&&verified("gemini")),new HuggingFaceAdapter(env.HF_SPACE_URL,env.HF_READY==="true"&&verified("huggingface")),new NoAiProvider()],undefined,{openrouter:openRemaining});
  const result=await gateway.execute({...body,requestId,allowExternalInference:body.allowExternalInference!==false});
  await env.DB.prepare("INSERT INTO ai_requests (id,workspace_id,recipe_id,task_type,data_class,preferred_mode,input_hash,status,created_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9)").bind(result.request.requestId,ctx.workspaceId,result.request.recipeId,result.request.taskType,result.request.dataClass,result.request.preferredMode,result.response.inputHash,result.response.status,result.response.receivedAt).run();
  await env.DB.prepare("INSERT INTO ai_responses (id,request_id,provider_id,model_id,status,output_json,raw_output_ref,input_hash,output_hash,latency_ms,limitations_json,received_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12)").bind(crypto.randomUUID(),result.request.requestId,result.response.providerId,result.response.modelId??null,result.response.status,result.response.output===undefined?null:JSON.stringify(result.response.output),result.response.rawOutputRef??null,result.response.inputHash,result.response.outputHash??null,result.response.latencyMs??null,JSON.stringify(result.response.limitations??[]),result.response.receivedAt).run();
  if(["openrouter","gemini","huggingface"].includes(result.response.providerId)) await recordQuota(env,ctx,result.response.providerId,result.response);
  await audit(env,ctx,result.response.status==="SUCCESS"?"AI_REQUEST_COMPLETED":"AI_PROVIDER_FAILED","AI_REQUEST",result.request.requestId,{provider:result.response.providerId,status:result.response.status});
  return result;
}
const recordTables:Record<string,string>={
  campaigns:"campaigns",content:"content_items",tasks:"tasks",research:"research_items",influencers:"influencers",applications:"applications",
  content_calendar:"content_calendar",keywords:"keywords",outreach_messages:"outreach_messages",assets:"assets",metric_snapshots:"metric_snapshots",
  reports:"reports",portfolio_items:"portfolio_items",sops:"sops",ai_providers:"ai_providers",platform_accounts:"platform_accounts",
  platform_connections:"platform_connections",brand_profiles:"brand_profiles",provider_capabilities:"provider_capabilities",prompt_templates:"prompt_templates",publication_evidence:"publication_evidence"
};
const recordResources=new Set(Object.keys(recordTables));
async function listRecords(env:Env,ctx:RequestContext,resource:string):Promise<unknown[]>{
  const table=recordTables[resource];
  if(!table)throw Object.assign(new Error("RESOURCE_NOT_ALLOWED"),{status:400});
  const r=await env.DB.prepare(`SELECT * FROM ${table} WHERE workspace_id=?1 ORDER BY created_at DESC LIMIT 100`).bind(ctx.workspaceId).all();return r.results||[];
}
async function createRecord(env:Env,ctx:RequestContext,request:Request,resource:string,body:any){return withIdempotency(env,ctx,request,`create_${resource}`,async()=>{const id=crypto.randomUUID();const now=new Date().toISOString();
  const val=(camel:string,snake=camel)=>body?.[camel]??body?.[snake];
  if(resource==="campaigns"){const name=str(body,"name"),objective=str(body,"objective"),audience=str(body,"audience"),message=str(body,"message");const channelsJson=val("channelsJson","channels_json")||"[]";const plannedRaw=val("plannedBudget","planned_budget");const plannedBudget=plannedRaw==null||plannedRaw===""?null:Number(plannedRaw);if(plannedBudget!==null&&!Number.isFinite(plannedBudget))throw Object.assign(new Error("INVALID_PLANNED_BUDGET"),{status:400});await env.DB.prepare("INSERT INTO campaigns (id,workspace_id,name,objective,audience,message,channels_json,status,planned_budget,actual_spend,actual_spend_status,approval_state,start_date,end_date,account_ref,creative_refs_json,copy_refs_json,placement,currency,tracking_plan,created_at,updated_at) VALUES (?1,?2,?3,?4,?5,?6,?7,'PLANNED',?8,NULL,'UNKNOWN','PENDING',?9,?10,?11,?12,?13,?14,?15,?16,?17,?17)").bind(id,ctx.workspaceId,name,objective,audience,message,channelsJson,plannedBudget,val("startDate","start_date")||null,val("endDate","end_date")||null,val("accountRef","account_ref")||null,val("creativeRefsJson","creative_refs_json")||"[]",val("copyRefsJson","copy_refs_json")||"[]",val("placement")||null,val("currency")||null,val("trackingPlan","tracking_plan")||null,now).run();}
  else if(resource==="content"){const title=str(body,"title"),objective=str(body,"objective"),audience=str(body,"audience"),coreMessage=str(body,"coreMessage","core_message"),platform=val("platform")||"UNKNOWN",cta=str(body,"cta"),draftBody=typeof val("draftBody","draft_body")==="string"?val("draftBody","draft_body"):"",contentType=val("contentType","content_type")||"SOCIAL_POST",campaignId=val("campaignId","campaign_id")||null;if(campaignId){const campaign=await env.DB.prepare("SELECT id FROM campaigns WHERE id=?1 AND workspace_id=?2").bind(campaignId,ctx.workspaceId).first();if(!campaign)throw Object.assign(new Error("CAMPAIGN_NOT_FOUND"),{status:404});}await env.DB.prepare("INSERT INTO content_items (id,workspace_id,campaign_id,title,content_type,objective,audience,core_message,platforms_json,draft_body,cta,source_refs_json,asset_refs_json,status,approval_state,scheduled_at,published_at,created_at,updated_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,'[]','[]','IDEA','PENDING',NULL,NULL,?12,?12)").bind(id,ctx.workspaceId,campaignId,title,contentType,objective,audience,coreMessage,JSON.stringify([platform]),draftBody,cta,now).run();}
  else if(resource==="tasks"){const title=str(body,"title");await env.DB.prepare("INSERT INTO tasks (id,workspace_id,title,description,area,priority,status,due_at,owner_user_id,linked_record_type,linked_record_id,next_action,created_at,updated_at) VALUES (?1,?2,?3,?4,?5,?6,'TODAY',?7,?8,NULL,NULL,'Review task',?9,?9)").bind(id,ctx.workspaceId,title,val("description")||null,val("area")||"GENERAL",val("priority")||"NORMAL",val("dueAt","due_at")||null,ctx.userId,now).run();}
  else if(resource==="research"){const topic=str(body,"topic"),sourceUrl=str(body,"sourceUrl","source_url"),sourceTitle=str(body,"sourceTitle","source_title");await env.DB.prepare("INSERT INTO research_items (id,workspace_id,topic,source_url,source_title,source_type,published_at,captured_at,summary,observations,implications,content_opportunities,campaign_opportunities,confidence) VALUES (?1,?2,?3,?4,?5,?6,NULL,?7,?8,?9,?10,?11,?12,?13)").bind(id,ctx.workspaceId,topic,sourceUrl,sourceTitle,val("sourceType","source_type")||"USER_CAPTURED",now,val("summary")||"",val("observations")||"",val("implications")||"",val("contentOpportunities","content_opportunities")||"",val("campaignOpportunities","campaign_opportunities")||"",val("confidence")||"UNKNOWN").run();}
  else if(resource==="influencers"){const name=str(body,"name"),platform=str(body,"platform"),profileUrl=str(body,"profileUrl","profile_url"),source=str(body,"source");await env.DB.prepare("INSERT INTO influencers (id,workspace_id,name,platform,profile_url,niche,audience,location_if_public,contact_method,fit_notes,source,status,last_contact,next_action,campaign_ids_json,created_at,updated_at) VALUES (?1,?2,?3,?4,?5,?6,NULL,NULL,NULL,NULL,?7,'DISCOVERED',NULL,'Research fit', '[]',?8,?8)").bind(id,ctx.workspaceId,name,platform,profileUrl,val("niche")||null,source,now).run();}
  else if(resource==="applications"){const company=str(body,"company"),role=str(body,"role"),jobUrl=str(body,"jobUrl","job_url"),source=str(body,"source"),status=val("status")||"DRAFT";await env.DB.prepare("INSERT INTO applications (id,workspace_id,company,role,job_url,source,date_found,date_applied,resume_version,cover_letter_version,portfolio_version,status,recruiter,follow_up_at,interview_at,notes,outcome,created_at,updated_at) VALUES (?1,?2,?3,?4,?5,?6,?7,NULL,NULL,NULL,NULL,?8,NULL,?9,NULL,?10,NULL,?11,?11)").bind(id,ctx.workspaceId,company,role,jobUrl,source,now,status,val("followUpAt","follow_up_at")||null,val("notes")||null,now).run();}
  else if(resource==="content_calendar"){const date=str(body,"date"),time=str(body,"time"),platform=str(body,"platform"),contentId=str(body,"contentId","content_id");const content=await env.DB.prepare("SELECT id,status,approval_state FROM content_items WHERE id=?1 AND workspace_id=?2").bind(contentId,ctx.workspaceId).first<any>();if(!content)throw Object.assign(new Error("CONTENT_NOT_FOUND"),{status:404});if(content.status!=="APPROVED"&&content.status!=="SCHEDULED")throw Object.assign(new Error("CALENDAR_REQUIRES_APPROVED_CONTENT"),{status:409});const campaignId=val("campaignId","campaign_id")||null;if(campaignId){const campaign=await env.DB.prepare("SELECT id FROM campaigns WHERE id=?1 AND workspace_id=?2").bind(campaignId,ctx.workspaceId).first();if(!campaign)throw Object.assign(new Error("CAMPAIGN_NOT_FOUND"),{status:404});}await env.DB.prepare("INSERT INTO content_calendar (id,workspace_id,date,time,platform,content_id,campaign_id,status,asset_status,approval_status,execution_status) VALUES (?1,?2,?3,?4,?5,?6,?7,'PLANNED','UNKNOWN','APPROVED','READY')").bind(id,ctx.workspaceId,date,time,platform,contentId,campaignId).run();}
  else if(resource==="keywords"){const keyword=str(body,"keyword"),source=str(body,"source");await env.DB.prepare("INSERT INTO keywords (id,workspace_id,keyword,source,intent,topic,volume_if_available,difficulty_if_available,priority,content_opportunity,pinterest_opportunity,blog_opportunity,status) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,'','','','IDEA')").bind(id,ctx.workspaceId,keyword,source,val("intent")||"UNKNOWN",val("topic")||null,val("volumeIfAvailable","volume_if_available")||null,val("difficultyIfAvailable","difficulty_if_available")||null,val("priority")||"NORMAL").run();}
  else if(resource==="outreach_messages"){const influencerId=str(body,"influencerId","influencer_id"),messageBody=str(body,"messageBody","message_body");const influencer=await env.DB.prepare("SELECT id FROM influencers WHERE id=?1 AND workspace_id=?2").bind(influencerId,ctx.workspaceId).first();if(!influencer)throw Object.assign(new Error("INFLUENCER_NOT_FOUND"),{status:404});const campaignId=val("campaignId","campaign_id")||null;if(campaignId){const campaign=await env.DB.prepare("SELECT id FROM campaigns WHERE id=?1 AND workspace_id=?2").bind(campaignId,ctx.workspaceId).first();if(!campaign)throw Object.assign(new Error("CAMPAIGN_NOT_FOUND"),{status:404});}await env.DB.prepare("INSERT INTO outreach_messages (id,workspace_id,influencer_id,campaign_id,idempotency_key,message_body,status,reviewed_by,sent_at,created_at) VALUES (?1,?2,?3,?4,?5,?6,'DRAFT',NULL,NULL,?7)").bind(id,ctx.workspaceId,influencerId,campaignId,crypto.randomUUID(),messageBody,now).run();}
  else if(resource==="assets"){const filename=str(body,"filename"),mimeType=str(body,"mimeType","mime_type"),assetType=str(body,"assetType","asset_type"),version=str(body,"version"),source=str(body,"source"),checksum=str(body,"checksum"),storageRef=str(body,"storageRef","storage_ref");await env.DB.prepare("INSERT INTO assets (id,workspace_id,campaign_id,filename,mime_type,asset_type,platforms_json,version,source,license,checksum,storage_ref,approval_status,created_at,updated_at) VALUES (?1,?2,?3,?4,?5,?6,'[]',?7,?8,?9,?10,?11,'PENDING',?12,?12)").bind(id,ctx.workspaceId,val("campaignId","campaign_id")||null,filename,mimeType,assetType,version,source,val("license")||null,checksum,storageRef,now).run();}
  else if(resource==="metric_snapshots"){await env.DB.prepare("INSERT INTO metric_snapshots (id,workspace_id,platform,campaign_id,content_id,metric_name,value_json,period_start,period_end,provider,source_ref,retrieved_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12)").bind(id,ctx.workspaceId,str(body,"platform"),val("campaignId","campaign_id")||null,val("contentId","content_id")||null,str(body,"metricName","metric_name"),str(body,"valueJson","value_json"),str(body,"periodStart","period_start"),str(body,"periodEnd","period_end"),str(body,"provider"),val("sourceRef","source_ref")||null,now).run();}
  else if(resource==="reports"){await env.DB.prepare("INSERT INTO reports (id,workspace_id,period_start,period_end,measured_facts_json,interpretation_json,next_priorities_json,open_risks_json,generated_by,created_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,'DETERMINISTIC',?9)").bind(id,ctx.workspaceId,str(body,"periodStart","period_start"),str(body,"periodEnd","period_end"),str(body,"measuredFactsJson","measured_facts_json"),str(body,"interpretationJson","interpretation_json"),val("nextPrioritiesJson","next_priorities_json")||"[]",val("openRisksJson","open_risks_json")||"[]",now).run();}
  else if(resource==="portfolio_items"){await env.DB.prepare("INSERT INTO portfolio_items (id,workspace_id,title,origin_label,metric_status,description,evidence_refs_json,created_at,updated_at) VALUES (?1,?2,?3,?4,?5,?6,'[]',?7,?7)").bind(id,ctx.workspaceId,str(body,"title"),val("originLabel","origin_label")||"SELF-DIRECTED SPEC",val("metricStatus","metric_status")||"UNKNOWN",str(body,"description"),now).run();}
  else if(resource==="sops"){await env.DB.prepare("INSERT INTO sops (id,workspace_id,name,cadence,steps_json,created_at,updated_at) VALUES (?1,?2,?3,?4,?5,?6,?6)").bind(id,ctx.workspaceId,str(body,"name"),val("cadence")||"AD_HOC",str(body,"stepsJson","steps_json"),now).run();}
  else if(resource==="ai_providers"){const providerState=val("state")||"NOT_CONFIGURED";if(providerState==="READY")throw Object.assign(new Error("PROVIDER_CAPABILITY_EVIDENCE_REQUIRED"),{status:409});await env.DB.prepare("INSERT INTO ai_providers (id,workspace_id,provider_id,state,capabilities_json,quota_state,last_checked_at,limitations_json) VALUES (?1,?2,?3,?4,?5,?6,?7,?8)").bind(id,ctx.workspaceId,str(body,"providerId","provider_id"),providerState,val("capabilitiesJson","capabilities_json")||"[]",val("quotaState","quota_state")||"UNKNOWN",now,val("limitationsJson","limitations_json")||"[]").run();}
  else if(resource==="provider_capabilities"){await env.DB.prepare("INSERT INTO provider_capabilities (id,workspace_id,provider_id,capability,ready,evidence_ref,checked_at) VALUES (?1,?2,?3,?4,?5,?6,?7)").bind(id,ctx.workspaceId,str(body,"providerId","provider_id"),str(body,"capability"),val("ready")?1:0,val("evidenceRef","evidence_ref")||null,now).run();}
  else if(resource==="platform_accounts"){await env.DB.prepare("INSERT INTO platform_accounts (id,workspace_id,platform,account_name,external_account_ref,state,created_at,updated_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?7)").bind(id,ctx.workspaceId,str(body,"platform"),val("accountName","account_name")||null,val("externalAccountRef","external_account_ref")||null,val("state")||"DISCONNECTED",now).run();}
  else if(resource==="platform_connections"){const connectionState=val("state")||"DISCONNECTED";if(connectionState==="READY")throw Object.assign(new Error("PLATFORM_CAPABILITY_EVIDENCE_REQUIRED"),{status:409});const platform=str(body,"platform");const accountId=val("platformAccountId","platform_account_id")||null;if(accountId){const account=await env.DB.prepare("SELECT id FROM platform_accounts WHERE id=?1 AND workspace_id=?2").bind(accountId,ctx.workspaceId).first();if(!account)throw Object.assign(new Error("PLATFORM_ACCOUNT_NOT_FOUND"),{status:404});}await env.DB.prepare("INSERT INTO platform_connections (id,workspace_id,platform,platform_account_id,state,capabilities_json,scopes_json,token_ref,token_expires_at,last_probe_at,limitations_json,created_at,updated_at) VALUES (?1,?2,?3,?4,?5,?6,?7,NULL,NULL,NULL,?8,?9,?9)").bind(id,ctx.workspaceId,platform,accountId,connectionState,val("capabilitiesJson","capabilities_json")||"[]",val("scopesJson","scopes_json")||"[]",val("limitationsJson","limitations_json")||"[]",now).run();}
  else if(resource==="brand_profiles"){await env.DB.prepare("INSERT INTO brand_profiles (id,workspace_id,brand_name,audience,voice,tone,do_rules_json,dont_rules_json,visual_rules_json,cta_rules_json,claim_rules_json,platform_rules_json,created_at,updated_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,'[]',?9,?10,'[]',?11,?11)").bind(id,ctx.workspaceId,str(body,"brandName","brand_name"),str(body,"audience"),str(body,"voice"),str(body,"tone"),val("doRulesJson","do_rules_json")||"[]",val("dontRulesJson","dont_rules_json")||"[]",val("ctaRulesJson","cta_rules_json")||"[]",val("claimRulesJson","claim_rules_json")||"[]",now).run();}
  else if(resource==="prompt_templates"){await env.DB.prepare("INSERT INTO prompt_templates (id,workspace_id,template_id,version,template_text,variables_hash,rendered_prompt_hash,created_at,updated_at) VALUES (?1,?2,?3,?4,?5,'UNKNOWN',NULL,?6,?6)").bind(id,ctx.workspaceId,str(body,"templateId","template_id"),str(body,"version"),str(body,"templateText","template_text"),now).run();}
  else throw Object.assign(new Error("RESOURCE_NOT_ALLOWED"),{status:400});
  await audit(env,ctx,"RECORD_CREATED",resource,id,{id});const created=await env.DB.prepare(`SELECT * FROM ${recordTables[resource]} WHERE id=?1 AND workspace_id=?2`).bind(id,ctx.workspaceId).first();return {id,workspaceId:ctx.workspaceId,record:created};});
}

async function contentAction(env:Env,ctx:RequestContext,request:Request,action:string,id:string){return withIdempotency(env,ctx,request,`content_${action}_${id}`,async()=>{const row=await env.DB.prepare("SELECT * FROM content_items WHERE id=?1 AND workspace_id=?2").bind(id,ctx.workspaceId).first<any>();if(!row)throw Object.assign(new Error("CONTENT_NOT_FOUND"),{status:404});
  if(action==="transition"){const body=await request.json() as any;const target=body.target as any;if(!["BRIEFED","DRAFT","QA","CHANGES_REQUIRED","ARCHIVED"].includes(target))throw Object.assign(new Error("CONTENT_TARGET_NOT_ALLOWED"),{status:400});if(!canTransitionContent(row.status,target))throw Object.assign(new Error(`INVALID_STATE_TRANSITION:${row.status}->${target}`),{status:409});const now=new Date().toISOString();await env.DB.prepare("UPDATE content_items SET status=?1,updated_at=?2 WHERE id=?3 AND workspace_id=?4").bind(target,now,id,ctx.workspaceId).run();await audit(env,ctx,"CONTENT_STATE_CHANGED","CONTENT",id,{from:row.status,to:target});return {id,status:target};}
  if(action==="approve"){if(!canTransitionContent(row.status,"APPROVED"))throw Object.assign(new Error("APPROVAL_REQUIRES_QA_STATE"),{status:409});await env.DB.prepare("UPDATE content_items SET status='APPROVED',approval_state='APPROVED',updated_at=?1 WHERE id=?2 AND workspace_id=?3").bind(new Date().toISOString(),id,ctx.workspaceId).run();await audit(env,ctx,"CONTENT_APPROVED","CONTENT",id,{status:"APPROVED"});return {id,status:"APPROVED"};}
  if(action==="schedule"){if(!canTransitionContent(row.status,"SCHEDULED"))throw Object.assign(new Error("SCHEDULE_REQUIRES_APPROVAL"),{status:409});const body=await request.json() as any;const scheduledAt=str(body,"scheduledAt");await env.DB.prepare("UPDATE content_items SET status='SCHEDULED',scheduled_at=?1,updated_at=?2 WHERE id=?3 AND workspace_id=?4").bind(scheduledAt,new Date().toISOString(),id,ctx.workspaceId).run();await audit(env,ctx,"POST_SCHEDULED","CONTENT",id,{scheduledAt});return {id,status:"SCHEDULED",scheduledAt};}
  if(action==="manual-confirm"){const body=await request.json() as any;const evidence=body.evidence==="CONFIRMED"||body.evidence==="MANUAL_CONFIRMED"?body.evidence:"UNKNOWN";const platforms=body.platform?[String(body.platform)]:(()=>{try{const parsed=JSON.parse(row.platforms_json||"[]");return Array.isArray(parsed)&&parsed.length?[String(parsed[0])]:["UNKNOWN"];}catch{return ["UNKNOWN"];}})();const platform=platforms[0];const existingEvidence=await env.DB.prepare("SELECT id FROM publication_evidence WHERE workspace_id=?1 AND content_id=?2 AND platform=?3 AND status IN ('PUBLISHED','CONFIRMED_MANUAL') LIMIT 1").bind(ctx.workspaceId,id,platform).first();if(existingEvidence)throw Object.assign(new Error("DUPLICATE_PUBLICATION"),{status:409});const decision=canPublish({current:row.status,target:"PUBLISHED",approvalState:row.approval_state,approvalRequired:true,evidence,duplicate:false});if(!decision.allowed)throw Object.assign(new Error(decision.reason),{status:409});const now=new Date().toISOString();const evidenceId=crypto.randomUUID();await env.DB.batch([env.DB.prepare("UPDATE content_items SET status='PUBLISHED',published_at=?1,updated_at=?1 WHERE id=?2 AND workspace_id=?3").bind(now,id,ctx.workspaceId),env.DB.prepare("INSERT INTO publication_evidence (id,workspace_id,content_id,platform,provider,status,evidence_ref,provider_post_id,confirmed_by,confirmed_at,request_id,created_at) VALUES (?1,?2,?3,?4,'MANUAL','PUBLISHED',?5,?6,?7,?8,?9,?8)").bind(evidenceId,ctx.workspaceId,id,platform,body.evidenceRef||evidence,body.providerPostId||null,ctx.userId,now,request.headers.get('idempotency-key'))]);await audit(env,ctx,"POST_PUBLISHED","CONTENT",id,{evidence,platform,evidenceId});return {id,status:"PUBLISHED",evidence,platform,evidenceId};}
  throw Object.assign(new Error("CONTENT_ACTION_NOT_ALLOWED"),{status:400});
});}
const updateColumns:Record<string,Set<string>>={
  campaigns:new Set(["name","objective","audience","message","channels_json","start_date","end_date","planned_budget","status","approval_state","account_ref","creative_refs_json","copy_refs_json","placement","currency","tracking_plan"]),
  content:new Set(["title","content_type","objective","audience","core_message","draft_body","cta","status","approval_state","scheduled_at"]),
  tasks:new Set(["title","description","area","priority","status","due_at","next_action","linked_record_type","linked_record_id"]),
  research:new Set(["topic","source_url","source_title","source_type","summary","observations","implications","content_opportunities","campaign_opportunities","confidence"]),
  influencers:new Set(["name","platform","profile_url","niche","audience","location_if_public","contact_method","fit_notes","status","last_contact","next_action"]),
  applications:new Set(["company","role","job_url","source","status","follow_up_at","interview_at","notes","outcome","resume_version","cover_letter_version","portfolio_version"]),
  content_calendar:new Set(["date","time","platform","campaign_id","status","asset_status","approval_status","execution_status"]),
  keywords:new Set(["keyword","source","intent","topic","volume_if_available","difficulty_if_available","priority","content_opportunity","pinterest_opportunity","blog_opportunity","status"]),
  outreach_messages:new Set(["campaign_id","message_body","status","reviewed_by"]),
  assets:new Set(["campaign_id","filename","mime_type","asset_type","platforms_json","version","source","license","checksum","storage_ref","approval_status"]),
  metric_snapshots:new Set(["platform","campaign_id","content_id","metric_name","value_json","period_start","period_end","provider","source_ref"]),
  reports:new Set(["period_start","period_end","measured_facts_json","interpretation_json","next_priorities_json","open_risks_json"]),
  portfolio_items:new Set(["title","origin_label","metric_status","description","evidence_refs_json"]),
  sops:new Set(["name","cadence","steps_json"]),
  ai_providers:new Set(["provider_id","state","capabilities_json","quota_state","last_checked_at","limitations_json"]),
  platform_accounts:new Set(["platform","account_name","external_account_ref","state"]),
  platform_connections:new Set(["platform","platform_account_id","state","capabilities_json","scopes_json","token_expires_at","last_probe_at","limitations_json"]),
  brand_profiles:new Set(["brand_name","audience","voice","tone","do_rules_json","dont_rules_json","visual_rules_json","cta_rules_json","claim_rules_json","platform_rules_json"]),
  provider_capabilities:new Set(["provider_id","capability","ready","evidence_ref","checked_at"]),
  prompt_templates:new Set(["template_id","version","template_text","variables_hash","rendered_prompt_hash"]),
  publication_evidence:new Set(["content_id","platform","provider","status","evidence_ref","provider_post_id","confirmed_by","confirmed_at","request_id"])
};
function dbColumn(k:string){return ({coreMessage:"core_message",contentType:"content_type",draftBody:"draft_body",campaignId:"campaign_id",sourceUrl:"source_url",sourceTitle:"source_title",sourceType:"source_type",profileUrl:"profile_url",fitNotes:"fit_notes",dueAt:"due_at",plannedBudget:"planned_budget",startDate:"start_date",endDate:"end_date",contentId:"content_id",volumeIfAvailable:"volume_if_available",difficultyIfAvailable:"difficulty_if_available",messageBody:"message_body",metricName:"metric_name",valueJson:"value_json",periodStart:"period_start",periodEnd:"period_end",sourceRef:"source_ref",mimeType:"mime_type",assetType:"asset_type",storageRef:"storage_ref",originLabel:"origin_label",metricStatus:"metric_status",jobUrl:"job_url",followUpAt:"follow_up_at",brandName:"brand_name",doRulesJson:"do_rules_json",dontRulesJson:"dont_rules_json",ctaRulesJson:"cta_rules_json",claimRulesJson:"claim_rules_json",providerId:"provider_id",capabilitiesJson:"capabilities_json",quotaState:"quota_state",limitationsJson:"limitations_json",scopesJson:"scopes_json",stepsJson:"steps_json",measuredFactsJson:"measured_facts_json",interpretationJson:"interpretation_json",nextPrioritiesJson:"next_priorities_json",openRisksJson:"open_risks_json",templateId:"template_id",templateText:"template_text",externalAccountRef:"external_account_ref",accountName:"account_name",platformAccountId:"platform_account_id",tokenExpiresAt:"token_expires_at",lastProbeAt:"last_probe_at",accountRef:"account_ref",creativeRefsJson:"creative_refs_json",copyRefsJson:"copy_refs_json",placement:"placement",currency:"currency",trackingPlan:"tracking_plan"}[k]||k);}
async function updateRecord(env:Env,ctx:RequestContext,request:Request,resource:string,id:string,body:any){return withIdempotency(env,ctx,request,`update_${resource}_${id}`,async()=>{const table=recordTables[resource];if(!table||!updateColumns[resource])throw Object.assign(new Error("RESOURCE_NOT_ALLOWED"),{status:400});const existing=await env.DB.prepare(`SELECT * FROM ${table} WHERE id=?1 AND workspace_id=?2`).bind(id,ctx.workspaceId).first<any>();if(!existing)throw Object.assign(new Error("RECORD_NOT_FOUND"),{status:404});if(resource==="platform_connections"&&body?.state==="READY"){const capabilities=String(body?.capabilitiesJson||body?.capabilities_json||existing.capabilities_json||"");if(!capabilities||capabilities==="[]"||!existing.last_probe_at)throw Object.assign(new Error("PLATFORM_CAPABILITY_EVIDENCE_REQUIRED"),{status:409});}if(resource==="ai_providers"&&body?.state==="READY"){const pid=body?.providerId||body?.provider_id||existing.provider_id;const verified=await env.DB.prepare("SELECT 1 FROM provider_capabilities WHERE workspace_id=?1 AND provider_id=?2 AND ready=1 AND evidence_ref IS NOT NULL AND evidence_ref!='' LIMIT 1").bind(ctx.workspaceId,pid).first();if(!verified)throw Object.assign(new Error("PROVIDER_CAPABILITY_EVIDENCE_REQUIRED"),{status:409});}const entries=Object.entries(body||{}).map(([k,v])=>[dbColumn(k),v] as const).filter(([k])=>updateColumns[resource].has(k));if(!entries.length)return {record:existing,id};const sets=entries.map(([k])=>`${k}=?`).join(',');const values=entries.map(([,v])=>v);const auditUpdatedTables=new Set(["campaigns","content","tasks","research","influencers","applications","outreach_messages","assets","portfolio_items","sops","ai_providers","platform_accounts","platform_connections","brand_profiles","prompt_templates"]);if(auditUpdatedTables.has(resource))await env.DB.prepare(`UPDATE ${table} SET ${sets},updated_at=? WHERE id=? AND workspace_id=?`).bind(...values,new Date().toISOString(),id,ctx.workspaceId).run();else await env.DB.prepare(`UPDATE ${table} SET ${sets} WHERE id=? AND workspace_id=?`).bind(...values,id,ctx.workspaceId).run();await audit(env,ctx,"RECORD_UPDATED",resource,id,{fields:entries.map(([k])=>k)});const updated=await env.DB.prepare(`SELECT * FROM ${table} WHERE id=?1 AND workspace_id=?2`).bind(id,ctx.workspaceId).first();return {id,record:updated};});}

async function recordAction(env:Env,ctx:RequestContext,request:Request,resource:string,id:string,action:string,body:any){return withIdempotency(env,ctx,request,`action_${resource}_${id}_${action}`,async()=>{
  const table=recordTables[resource];if(!table)throw Object.assign(new Error("RESOURCE_NOT_ALLOWED"),{status:400});const row=await env.DB.prepare(`SELECT * FROM ${table} WHERE id=?1 AND workspace_id=?2`).bind(id,ctx.workspaceId).first<any>();if(!row)throw Object.assign(new Error("RECORD_NOT_FOUND"),{status:404});const now=new Date().toISOString();
  if(resource==="tasks"){const transitions:Record<string,string>={START:"IN_PROGRESS",DONE:"DONE",CANCEL:"CANCELLED",REOPEN:"TODAY",WAIT:"WAITING",REVIEW:"REVIEW"};if(!transitions[action])throw Object.assign(new Error("TASK_ACTION_NOT_ALLOWED"),{status:400});if(action==="START"&&row.status!=="TODAY"&&row.status!=="BACKLOG")throw Object.assign(new Error("TASK_START_REQUIRES_TODAY_OR_BACKLOG"),{status:409});if(action==="REOPEN"&&row.status!=="DONE")throw Object.assign(new Error("TASK_REOPEN_REQUIRES_DONE"),{status:409});await env.DB.prepare("UPDATE tasks SET status=?,updated_at=? WHERE id=? AND workspace_id=?").bind(transitions[action],now,id,ctx.workspaceId).run();}
  else if(resource==="campaigns"){const transitions:Record<string,string>={ACTIVATE:"ACTIVE",PAUSE:"PAUSED",COMPLETE:"COMPLETED",ARCHIVE:"ARCHIVED"};if(!transitions[action])throw Object.assign(new Error("CAMPAIGN_ACTION_NOT_ALLOWED"),{status:400});if(action==="ACTIVATE"&&!["PLANNED","PAUSED"].includes(row.status))throw Object.assign(new Error("CAMPAIGN_ACTIVATE_REQUIRES_PLANNED_OR_PAUSED"),{status:409});if(action==="PAUSE"&&row.status!=="ACTIVE")throw Object.assign(new Error("CAMPAIGN_PAUSE_REQUIRES_ACTIVE"),{status:409});await env.DB.prepare("UPDATE campaigns SET status=?,updated_at=? WHERE id=? AND workspace_id=?").bind(transitions[action],now,id,ctx.workspaceId).run();}
  else if(resource==="influencers"){const transitions:Record<string,string>={RESEARCH:"RESEARCHING",QUALIFY:"QUALIFIED",CONTACT:"CONTACTED",ARCHIVE:"ARCHIVED"};if(!transitions[action])throw Object.assign(new Error("INFLUENCER_ACTION_NOT_ALLOWED"),{status:400});await env.DB.prepare("UPDATE influencers SET status=?,next_action=?,updated_at=? WHERE id=? AND workspace_id=?").bind(transitions[action],action==="ARCHIVE"?"No active next action":"Review fit and source",now,id,ctx.workspaceId).run();}
  else if(resource==="applications"){if(action==="READY_TO_SUBMIT"){if(!["DRAFT","UNKNOWN"].includes(row.status))throw Object.assign(new Error("APPLICATION_READY_STATE_NOT_ALLOWED"),{status:409});await env.DB.prepare("UPDATE applications SET status='READY_TO_SUBMIT',updated_at=? WHERE id=? AND workspace_id=?").bind(now,id,ctx.workspaceId).run();}else if(action==="CONFIRM_SUBMISSION"){if(row.status!=="READY_TO_SUBMIT")throw Object.assign(new Error("APPLICATION_SUBMISSION_REQUIRES_READY_STATE"),{status:409});const evidence=str(body,"evidence");if(evidence!=="USER_CONFIRMED")throw Object.assign(new Error("SUBMISSION_CONFIRMATION_REQUIRED"),{status:400});await env.DB.prepare("UPDATE applications SET status='SUBMITTED',date_applied=?,updated_at=? WHERE id=? AND workspace_id=?").bind(now,now,id,ctx.workspaceId).run();}else if(action==="INTERVIEW")await env.DB.prepare("UPDATE applications SET status='INTERVIEW',updated_at=? WHERE id=? AND workspace_id=?").bind(now,id,ctx.workspaceId).run();else throw Object.assign(new Error("APPLICATION_ACTION_NOT_ALLOWED"),{status:400});}
  else if(resource==="outreach_messages"){if(action==="REVIEW")await env.DB.prepare("UPDATE outreach_messages SET status='REVIEW',reviewed_by=? WHERE id=? AND workspace_id=?").bind(ctx.userId,id,ctx.workspaceId).run();else if(action==="READY_TO_SEND")await env.DB.prepare("UPDATE outreach_messages SET status='READY_TO_SEND',reviewed_by=? WHERE id=? AND workspace_id=?").bind(ctx.userId,id,ctx.workspaceId).run();else if(action==="MANUAL_SEND_CONFIRMED"){if(row.status!=="READY_TO_SEND")throw Object.assign(new Error("OUTREACH_SEND_REQUIRES_READY_STATE"),{status:409});await env.DB.prepare("UPDATE outreach_messages SET status='SENT',sent_at=?,reviewed_by=? WHERE id=? AND workspace_id=?").bind(now,ctx.userId,id,ctx.workspaceId).run();await audit(env,ctx,"OUTREACH_SENT",resource,id,{confirmedBy:ctx.userId});}else throw Object.assign(new Error("OUTREACH_ACTION_NOT_ALLOWED"),{status:400});}
  else if(resource==="content_calendar"){if(action==="MANUAL_HANDOFF")await env.DB.prepare("UPDATE content_calendar SET execution_status='MANUAL_ONLY',status='MANUAL_ONLY' WHERE id=? AND workspace_id=?").bind(id,ctx.workspaceId).run();else if(action==="MARK_PUBLISHED"){if(!["READY","SCHEDULED","MANUAL_ONLY"].includes(row.status))throw Object.assign(new Error("PUBLICATION_STATE_NOT_ALLOWED"),{status:409});const evidence=str(body,"evidence");if(evidence!=="USER_CONFIRMED")throw Object.assign(new Error("PUBLICATION_CONFIRMATION_REQUIRED"),{status:400});if(!row.content_id)throw Object.assign(new Error("CONTENT_REFERENCE_REQUIRED"),{status:400});const content=await env.DB.prepare("SELECT id,status,approval_state FROM content_items WHERE id=?1 AND workspace_id=?2").bind(row.content_id,ctx.workspaceId).first<any>();if(!content)throw Object.assign(new Error("CONTENT_REFERENCE_NOT_FOUND"),{status:404});if(content.approval_state!=="APPROVED"&&content.status!=="PUBLISHED")throw Object.assign(new Error("PUBLICATION_APPROVAL_REQUIRED"),{status:409});const existingEvidence=await env.DB.prepare("SELECT id FROM publication_evidence WHERE workspace_id=?1 AND content_id=?2 AND platform=?3 AND status IN ('PUBLISHED','CONFIRMED_MANUAL') LIMIT 1").bind(ctx.workspaceId,row.content_id,row.platform).first();if(existingEvidence)throw Object.assign(new Error("DUPLICATE_PUBLICATION"),{status:409});const now=new Date().toISOString();const evidenceId=crypto.randomUUID();await env.DB.batch([env.DB.prepare("UPDATE content_calendar SET execution_status='PUBLISHED',status='PUBLISHED' WHERE id=? AND workspace_id=?").bind(id,ctx.workspaceId),env.DB.prepare("UPDATE content_items SET status='PUBLISHED',published_at=?1,updated_at=?1 WHERE id=?2 AND workspace_id=?3").bind(now,row.content_id,ctx.workspaceId),env.DB.prepare("INSERT INTO publication_evidence (id,workspace_id,content_id,platform,provider,status,evidence_ref,provider_post_id,confirmed_by,confirmed_at,request_id,created_at) VALUES (?1,?2,?3,?4,'MANUAL','PUBLISHED',?5,?6,?7,?8,?9,?8)").bind(evidenceId,ctx.workspaceId,row.content_id,row.platform,evidence,body.providerPostId||null,ctx.userId,now,request.headers.get('idempotency-key'))]);}else throw Object.assign(new Error("CALENDAR_ACTION_NOT_ALLOWED"),{status:400});}
  else if(resource==="platform_connections"){if(action!=="PROBE")throw Object.assign(new Error("CONNECTION_ACTION_NOT_ALLOWED"),{status:400});const probeResult=str(body,"probeResult");const evidenceRef=body?.evidenceRef?String(body.evidenceRef).trim():"";const capabilitiesJson=body?.capabilitiesJson||body?.capabilities_json||row.capabilities_json||"[]";if(probeResult==="READY"&&!evidenceRef)throw Object.assign(new Error("PLATFORM_CAPABILITY_EVIDENCE_REQUIRED"),{status:409});let normalizedCapabilities:string;try{JSON.parse(String(capabilitiesJson));normalizedCapabilities=String(capabilitiesJson);}catch{throw Object.assign(new Error("CAPABILITIES_JSON_INVALID"),{status:400});}const limitationSuffix=evidenceRef?`Probe evidence: ${evidenceRef}`:"Probe recorded without external evidence reference.";let limitations:any[]=[];try{limitations=JSON.parse(row.limitations_json||"[]");if(!Array.isArray(limitations))limitations=[];}catch{limitations=[];}const nextLimitations=limitations.filter((x:any)=>typeof x==="string"&&!x.startsWith("Probe evidence:")&&!x.startsWith("Probe recorded without"));nextLimitations.push(limitationSuffix);await env.DB.prepare("UPDATE platform_connections SET state=?,capabilities_json=?,last_probe_at=?,limitations_json=?,updated_at=? WHERE id=? AND workspace_id=?").bind(probeResult,normalizedCapabilities,now,JSON.stringify(nextLimitations),now,id,ctx.workspaceId).run();await audit(env,ctx,"PLATFORM_CONNECTION_PROBED","PLATFORM_CONNECTION",id,{probeResult,evidenceRef: evidenceRef||null,capabilities:normalizedCapabilities});}
  else if(resource==="ai_providers"){if(action!=="VERIFY_CAPABILITY"&&action!=="PROBE")throw Object.assign(new Error("PROVIDER_ACTION_NOT_ALLOWED"),{status:400});const pid=row.provider_id;let state=row.state;let limitations=JSON.parse(row.limitations_json||'[]');if(action==="VERIFY_CAPABILITY"){const capability=str(body,"capability");const evidenceRef=str(body,"evidenceRef","evidence_ref");if(!capability||!evidenceRef)throw Object.assign(new Error("CAPABILITY_EVIDENCE_REQUIRED"),{status:400});await env.DB.prepare("INSERT INTO provider_capabilities (id,workspace_id,provider_id,capability,ready,evidence_ref,checked_at) VALUES (?1,?2,?3,?4,1,?5,?6)").bind(crypto.randomUUID(),ctx.workspaceId,pid,capability,evidenceRef,now).run();state="READY";await env.DB.prepare("UPDATE ai_providers SET state=?,last_checked_at=?,updated_at=? WHERE id=? AND workspace_id=?").bind(state,now,id,ctx.workspaceId).run();await audit(env,ctx,"AI_PROVIDER_CAPABILITY_VERIFIED","AI_PROVIDER",id,{provider:pid,capability,evidenceRef});}else{if(pid==='openrouter'){state=env.OPENROUTER_API_KEY?(env.OPENROUTER_READY==='true'?'CONNECTED':'CONNECTED'):'NOT_CONFIGURED';}else if(pid==='gemini'){state=env.GEMINI_API_KEY?(env.GEMINI_READY==='true'?'CONNECTED':'CONNECTED'):'NOT_CONFIGURED';}else if(pid==='huggingface'){state=env.HF_SPACE_URL?(env.HF_READY==='true'?'CONNECTED':'CONNECTED'):'NOT_CONFIGURED';}else {state=row.state||'NOT_CONFIGURED';limitations=[...limitations,'No live capability adapter configured'];}await env.DB.prepare("UPDATE ai_providers SET state=?,last_checked_at=?,limitations_json=?,updated_at=? WHERE id=? AND workspace_id=?").bind(state,now,JSON.stringify(limitations),now,id,ctx.workspaceId).run();}}
  else throw Object.assign(new Error("ACTION_NOT_ALLOWED"),{status:400});
  await audit(env,ctx,"RECORD_ACTION",resource,id,{action});const updated=await env.DB.prepare(`SELECT * FROM ${table} WHERE id=?1 AND workspace_id=?2`).bind(id,ctx.workspaceId).first();return {id,record:updated,message:`${action} completed`};});}

async function aiDecision(env:Env,ctx:RequestContext,request:Request){return withIdempotency(env,ctx,request,"ai_decision",async()=>{const body=await request.json() as any;const requestId=str(body,"requestId");const decision=str(body,"decision");if(!["APPROVED_BY_HUMAN","CHANGES_REQUIRED"].includes(decision))throw Object.assign(new Error("AI_DECISION_NOT_ALLOWED"),{status:400});await audit(env,ctx,"AI_HUMAN_DECISION","AI_REQUEST",requestId,{decision});return {requestId,decision,recorded:true};});}
async function manualPrepare(env:Env,ctx:RequestContext,request:Request){const payload=await request.json() as any;const requestId=crypto.randomUUID();await audit(env,ctx,"AI_REQUEST_CREATED","AI_REQUEST",requestId,{mode:"MANUAL_BROWSER",recipeId:payload?.recipeId||null,taskType:payload?.taskType||null,dataClass:payload?.dataClass||"UNKNOWN"});return {state:"PROMPT_READY",requestId,prompt:payload};}
async function manualEvent(env:Env,ctx:RequestContext,request:Request){const body=await request.json() as any;const requestId=str(body,"requestId")||"MANUAL";const eventType=str(body,"eventType");if(!["MANUAL_AI_OPENED","MANUAL_AI_REVIEW_PENDING"].includes(eventType))throw Object.assign(new Error("MANUAL_EVENT_NOT_ALLOWED"),{status:400});await audit(env,ctx,eventType,"AI_REQUEST",requestId,{mode:"MANUAL_BROWSER"});return {requestId,eventType,recorded:true};}
async function providerStatus(env:Env,ctx:RequestContext){const openRemaining=await quotaFor(env,ctx,"openrouter");const saved=await env.DB.prepare("SELECT * FROM ai_providers WHERE workspace_id=?1 ORDER BY provider_id").bind(ctx.workspaceId).all();const savedMap=new Map((saved.results||[]).map((r:any)=>[r.provider_id,r]));const configured=[['openrouter',env.OPENROUTER_API_KEY,env.OPENROUTER_READY],['gemini',env.GEMINI_API_KEY,env.GEMINI_READY],['huggingface',env.HF_SPACE_URL,env.HF_READY]].map(([provider,key,ready])=>{const savedRow=savedMap.get(provider) as any;const quotaRemaining=provider==='openrouter'?openRemaining:undefined;const quotaState=provider==='openrouter'?(quotaRemaining===undefined?"UNKNOWN":quotaRemaining<=0?"LIMITED":quotaRemaining<=7?"NEAR_LIMIT":"AVAILABLE"):"UNKNOWN";return {...(savedRow||{}),provider_id:provider,state:savedRow?.state|| (key?"CONNECTED":"NOT_CONFIGURED"),capability_verified:savedRow?.state==="READY"&&ready==='true',quota_state:savedRow?.quota_state&&savedRow.quota_state!=="UNKNOWN"?savedRow.quota_state:quotaState,quota_remaining:quotaRemaining};});const extra=(saved.results||[]).filter((r:any)=>!configured.some(c=>c.provider_id===r.provider_id));const connections=await env.DB.prepare("SELECT * FROM platform_connections WHERE workspace_id=?1 ORDER BY platform").bind(ctx.workspaceId).all();return {providers:[...configured,...extra],connections:connections.results||[]};}
async function generateReport(env:Env,ctx:RequestContext,request:Request){return withIdempotency(env,ctx,request,"generate_report",async()=>{const now=new Date();const periodEnd=now.toISOString().slice(0,10);const start=new Date(now);start.setDate(start.getDate()-6);const periodStart=start.toISOString().slice(0,10);const counts:any={};for(const [key,table] of Object.entries({campaigns:"campaigns",content:"content_items",tasks:"tasks",metrics:"metric_snapshots",outreach:"outreach_messages",applications:"applications",assets:"assets"})){const r=await env.DB.prepare(`SELECT COUNT(*) AS c FROM ${table} WHERE workspace_id=?1`).bind(ctx.workspaceId).first<{c:number}>();counts[key]=Number(r?.c??0);}const unknown=await env.DB.prepare("SELECT COUNT(*) AS c FROM metric_snapshots WHERE workspace_id=?1 AND value_json='UNKNOWN'").bind(ctx.workspaceId).first<{c:number}>();const measuredFacts={periodStart,periodEnd,counts,unknownMetricSnapshots:Number(unknown?.c??0)};const interpretation={statements:[counts.metrics?"Use recorded source-backed metrics for reporting; do not infer missing values.":"No measured metric snapshots were recorded for this period.",counts.content?`${counts.content} content records are available for review.`:"No content records were recorded in the workspace.",counts.campaigns?`${counts.campaigns} campaign records are available.`:"No campaigns are recorded yet."],basis:"DETERMINISTIC_COUNTS_ONLY"};const nextPriorities=[counts.content?"Review content QA and approval states":"Create the first content records",counts.outreach?"Review outreach next actions":"Build the first outreach drafts",counts.applications?"Review application evidence and follow-ups":"Add application opportunities"];const openRisks=Number(unknown?.c??0)>0?["Some metric snapshots are explicitly UNKNOWN; do not treat them as zero."]:[];const id=crypto.randomUUID();await env.DB.prepare("INSERT INTO reports (id,workspace_id,period_start,period_end,measured_facts_json,interpretation_json,next_priorities_json,open_risks_json,generated_by,created_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,'DETERMINISTIC',?9)").bind(id,ctx.workspaceId,periodStart,periodEnd,JSON.stringify(measuredFacts),JSON.stringify(interpretation),JSON.stringify(nextPriorities),JSON.stringify(openRisks),now.toISOString()).run();await audit(env,ctx,"REPORT_GENERATED","REPORT",id,{generatedBy:"DETERMINISTIC"});return {id,record:await env.DB.prepare("SELECT * FROM reports WHERE id=?1 AND workspace_id=?2").bind(id,ctx.workspaceId).first()};});}

async function exportWorkspace(env:Env,ctx:RequestContext,origin:string):Promise<Response>{const tables=["campaigns","content_items","content_calendar","research_items","keywords","influencers","influencer_contacts","outreach_messages","assets","metric_snapshots","reports","applications","recipes","tasks","projects","ai_providers","ai_requests","ai_responses","ai_evaluations","provider_capabilities","platform_accounts","platform_connections","brand_profiles","publication_evidence","audit_events"];const data:Record<string,unknown[]>= {};for(const table of tables){const r=await env.DB.prepare(`SELECT * FROM ${table} WHERE workspace_id=?1`).bind(ctx.workspaceId).all();data[table]=r.results||[];}return json({exportVersion:"1.0.0",workspaceId:ctx.workspaceId,exportedAt:new Date().toISOString(),data,assetReferences:(data.assets||[]).map((a:any)=>a.storage_ref).filter(Boolean)}, {}, origin);}
export default {async fetch(request:Request,env:Env):Promise<Response>{
  const url=new URL(request.url),origin=env.FRONTEND_ORIGIN||"*";
  if(request.method==="OPTIONS")return new Response(null,{status:204,headers:{"access-control-allow-origin":origin,"access-control-allow-methods":"GET,POST,PATCH,OPTIONS","access-control-allow-headers":"content-type,idempotency-key,cf-access-authenticated-user-email,x-mow-workspace,x-mow-user"}});
  try{
    if(url.pathname==="/api/health")return json({ok:true,version:"1.0.0",ai_optional:true,authMode:env.DEMO_AUTH==="true"?"DEMO":"CLOUDFLARE_ACCESS"},{},origin);
    const ctx=await ctxFrom(request,env);
    if(url.pathname==="/api/dashboard")return json(await dashboard(env,ctx),{},origin);
    if(url.pathname==="/api/ai/generate"&&request.method==="POST")return json(await generate(env,request,ctx),{},origin);
    if(url.pathname==="/api/ai/qa"&&request.method==="POST")return json(evaluateDeterministically(await request.json()),{},origin);
    if(url.pathname==="/api/ai/kev"&&request.method==="POST"){const kev=env.KEV_ENDPOINT_URL?new HttpKevEvaluator(env.KEV_ENDPOINT_URL):new UnavailableKevEvaluator();return json(await kev.evaluate(await request.json()),{},origin);}
    if(url.pathname==="/api/manual/prepare"&&request.method==="POST")return json(await manualPrepare(env,ctx,request),{},origin);
    if(url.pathname==="/api/manual/event"&&request.method==="POST")return json(await manualEvent(env,ctx,request),{},origin);
    if(url.pathname==="/api/export"&&request.method==="GET")return exportWorkspace(env,ctx,origin);
    if(url.pathname==="/api/providers/status"&&request.method==="GET")return json(await providerStatus(env,ctx),{},origin);
    if(url.pathname==="/api/reports/generate"&&request.method==="POST")return json(await generateReport(env,ctx,request),{},origin);
    if(url.pathname==="/api/ai/decision"&&request.method==="POST")return json(await aiDecision(env,ctx,request),{},origin);
    const recordMatch=url.pathname.match(/^\/api\/records\/([^/]+)$/); if(recordMatch&&request.method==="GET")return json({data:await listRecords(env,ctx,recordMatch[1])}, {}, origin); if(recordMatch&&request.method==="POST")return json(await createRecord(env,ctx,request,recordMatch[1],await request.json()),{},origin);
    const recordIdMatch=url.pathname.match(/^\/api\/records\/([^/]+)\/([^/]+)$/); if(recordIdMatch&&request.method==="GET")return json({data:recordTables[recordIdMatch[1]]?await env.DB.prepare(`SELECT * FROM ${recordTables[recordIdMatch[1]]} WHERE id=?1 AND workspace_id=?2`).bind(recordIdMatch[2],ctx.workspaceId).first():null}, {}, origin); if(recordIdMatch&&request.method==="PATCH")return json(await updateRecord(env,ctx,request,recordIdMatch[1],recordIdMatch[2],await request.json()),{},origin);
    const contentMatch=url.pathname.match(/^\/api\/content\/([^/]+)\/(transition|approve|schedule|manual-confirm)$/);if(contentMatch&&request.method==="POST")return json(await contentAction(env,ctx,request,contentMatch[2],contentMatch[1]),{},origin);
    const actionMatch=url.pathname.match(/^\/api\/records\/([^/]+)\/([^/]+)\/actions$/); if(actionMatch&&request.method==="POST"){const body=await request.json() as any;return json(await recordAction(env,ctx,request,actionMatch[1],actionMatch[2],body.action,body),{},origin);}
    return json({code:"NOT_FOUND",message:"Route not found",retrySafe:false,workPreserved:true,publicationOccurred:"UNKNOWN",nextActions:["Check the route"]},{status:404},origin);
  }catch(error){const status=(error as any)?.status===401?401:(error as any)?.status===403?403:(error as any)?.status===400?400:(error as any)?.status===404?404:(error as any)?.status===409?409:500;return json({code:error instanceof Error?error.message:"WORKER_ERROR",message:error instanceof Error?error.message:"Unknown error",retrySafe:status<400,workPreserved:true,publicationOccurred:"UNKNOWN",nextActions:status===401?["Authenticate through Cloudflare Access"]:["Review the explicit error state","Retry only when safe"]},{status},origin);}
},async queue(batch:MessageBatch,env:Env){for(const message of batch.messages){try{const p=message.body as any;await env.DB.prepare("UPDATE jobs SET status='RUNNING',attempts=attempts+1,updated_at=?1 WHERE id=?2").bind(new Date().toISOString(),p.jobId).run();await env.DB.prepare("UPDATE jobs SET status='SUCCEEDED',updated_at=?1 WHERE id=?2").bind(new Date().toISOString(),p.jobId).run();message.ack();}catch(error){await env.DB.prepare("UPDATE jobs SET status=CASE WHEN attempts>=2 THEN 'DEAD_LETTER' ELSE 'FAILED' END,last_error=?1,updated_at=?2 WHERE id=?3").bind(error instanceof Error?error.message:"QUEUE_ERROR",new Date().toISOString(),(message.body as any).jobId).run();message.retry();}}}};
